blog/app.py
from flask import Flask

from blog.report.views import report
from blog.user.views import user


def create_app() -> Flask:
    app = Flask(__name__)
    register_blueprint(app)
    return app


def register_blueprint(app: Flask):
    app.register_blueprint(user)
    app.register_blueprint(report)

blog/report/views.py
from flask import Blueprint

report = Blueprint('report', __name__, url_prefix='/reports', static_folder='../static')


@report.route('/')
def report_list():
    return 'Hello, report!'

blog/user/views.py
from flask import Blueprint, render_template, redirect

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')

USERS = {
    1: 'Alice',
    2: 'Jon',
    3: 'Mike',
}


@user.route('/')
def user_list():
    return render_template(
        'users/list.html',
        users=USERS,
    )


@user.route('/<int:pk>')
def get_user(pk: int):
    try:
        user_name = USERS[pk]
    except KeyError:
        return redirect('/users/')
    return render_template(
        'users/details.html',
        user_name=user_name,
    )

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block css%}{% endblock%}
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
<div class="container">
  {% block body %}{% endblock %}
</div>

 {% block js %}{% endblock %}
</body>
</html>

blog/templates/users/details.html
{% extends 'base.html' %}

{% block title %}
    Users detail
{% endblock %}

{% block body %}
    <h1>{{ user_name }}:</h1>
{% endblock %}

blog/templates/users/list.html
{% extends 'base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <h1>Users:</h1>
    {% for user_id in users %}
        <ul>
            <li><a href="{{ url_for('user.get_user', pk=user_id) }}">{{ users[user_id] }}</a></li>
        </ul>
    {% endfor %}
{% endblock %}